### ISSUE TITLE
Pagination code is broken

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/patchwork#102]
Go to the second last page for a given Patchwork project with many pages (disabled all filters if this helps), like [this one](https://patchwork.ozlabs.org/project/patchwork/list/?state=*&page=15) (may be out-of-date). You'll note that there isn't an option to go to the third last page as you'd expect.

Now click the `«` to go back to the third last page. You'll note that the second last page is duplicated twice.

This appears to be a long running bug with the `paginator` code that we should probably fix up.

**Comment by daxtens** [comment]
This is still a bug. Will try to bash out a patch.
