### ISSUE TITLE
Mails with empty subjects seem to fail

### ISSUE THREAD

**Issue by daxtens** [getpatchwork/patchwork#108]
This is as a result of my parsing fuzz fixes.

Observed on my patchwork.dja instances - admittedly the relevant emails were spam, but still apparently we see blank subjects, especially with cover letters.

(The issue is more as a reminder to me to fix it than a bug report.)

**Comment by daxtens** [comment]
Patch sent.

**Comment by ajdlinux** [comment]
That would appear to be https://github.com/getpatchwork/patchwork/commit/ae6cd3bcc76c34b9f449319a7de8859ba4705ca9. Closing this issue accordingly.
