### ISSUE TITLE
A/R/T not updated on comments

### ISSUE THREAD

**Issue by markand** [getpatchwork/patchwork#111]
Hi,

It looks like commenting on a mail with a line like:

    Reviewed-By: foo <address>

Does not update the A/R/T column. @philpep told me that a missing .save() call is missing.

**Comment by ajdlinux** [comment]
I'm seeing this on @daxtens' test setup at py3.patchwork.dja.id.au as well.

I'll try to take a look in the next few days when I've got time, it sounds like we're also missing a test case here.

**Comment by ajdlinux** [comment]
Taking a look at it now - at first glance it looks like we don't have any tests to check that the tag count is updating correctly :/

**Comment by ajdlinux** [comment]
OK, it looks like we're incorrectly invoking refresh_tag_counts() in Comment.save() - we're retrieving the submission via the Submission base class, and thus calling Submission.refresh_tag_counts() which is a stub.

Patch and test case incoming.

**Comment by ajdlinux** [comment]
I've sent a patch and a test: http://patchwork.ozlabs.org/patch/803733/

**Comment by ajdlinux** [comment]
hmm, seems github doesn't quite recognise "Closes-bug"?

Anyway, this is fixed in 866d14b and can be closed now

**Comment by stephenfin** [comment]
Indeed it can
