### ISSUE TITLE
Slightly misformatted tags are counted, but not included in mbox

### ISSUE THREAD

**Issue by ajdlinux** [getpatchwork/patchwork#124]
https://patchwork.ozlabs.org/patch/821166/

The comment:

`Acked-by:  Christophe Lombard<clombard@linux.vnet.ibm.com>`

is counted in the A/R/T on the patch list, but doesn't appear in the downloaded mbox. I suspect it's because Christophe forgot to add a space between his name and his email, and this is tripping up a regex somewhere, but I haven't looked at the code at all, so it could be something completely different

(Reported by @stewart-ibm)

**Comment by daxtens** [comment]
Confirmed. It my mbox there are 2 spaces between the colon and the C, that might be why? We have a test for "Acked-by: 1" and that seems to work...

**Comment by daxtens** [comment]
Ok, the space that emacs was showing me is a UTF-8 non-breaking space!

```
000008f0  3e 20 2d 2d 2d 0a 0a 41  63 6b 65 64 2d 62 79 3a  |> ---..Acked-by:|
00000900  c2 a0 20 43 68 72 69 73  74 6f 70 68 65 20 4c 6f  |.. Christophe Lo|
```

c2a0 is the UTF-8 for a non-breaking space.

We don't currently handle that in the parser. We probably can using the `[:space:]` class, I will investigate.
