### ISSUE TITLE
Series parsing gets confused by misformatted PATCH tag

### ISSUE THREAD

**Issue by ajdlinux** [getpatchwork/patchwork#126]
http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=6212

Missing space between PATCH and 1/8 seems to be confusing things. Needs further investigation

(Reported by @mpe)

**Comment by mpe** [comment]
Each patch ended up in a series by itself, eg:

http://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=6213

But if you look at the headers they were threaded correctly.
