### ISSUE TITLE
NoReverseMatch exception on user login with disabled REST API

### ISSUE THREAD

**Issue by stoupa-cz** [getpatchwork/patchwork#138]
Hi,

our patchwork works flawlessly, but when the REST API is disabled (i.e. `ENABLE_REST_API = False`) the page for logged in user is broken with NoReverseMatch exception:

<pre>
NoReverseMatch at /user/
Reverse for 'generate_token' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Request Method:	GET
Request URL:	https://XXX/patchwork/user/
Django Version:	1.10.8
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'generate_token' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location:	/opt/python_virtualenv/XXX_patchwork/lib/python2.7/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 392
Python Executable:	/usr/bin/python
Python Version:	2.7.5
Python Path:	
['/opt/patchwork',
 '/opt/python_virtualenv/XXX_patchwork/lib64/python27.zip',
 '/opt/python_virtualenv/XXX_patchwork/lib64/python2.7',
 '/opt/python_virtualenv/XXX_patchwork/lib64/python2.7/plat-linux2',
 '/opt/python_virtualenv/XXX_patchwork/lib64/python2.7/lib-tk',
 '/opt/python_virtualenv/XXX_patchwork/lib64/python2.7/lib-old',
 '/opt/python_virtualenv/XXX_patchwork/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7',
 '/usr/lib/python2.7',
 '/opt/python_virtualenv/XXX_patchwork/lib/python2.7/site-packages']
Server time:	Fri, 17 Nov 2017 02:32:05 +1100
</pre>

I'm using v2.0.0 tarball, the version in the footer is 2.0.0.alpha-0.

Please note that I don't need the disabled REST API. I just disabled various features during installation.

**Comment by ajdlinux** [comment]
Thanks - looks like I forgot to test this when I added token auth.

Patch sent.
