### ISSUE TITLE
Improve data processing for Unicode characters

### ISSUE THREAD

**Issue by elfring** [getpatchwork/patchwork#140]
I dared to use also special Unicode characters (like box drawing and emojis) in my messages with which I published patches.
I noticed then that the information display can become incomplete. Can the shown data truncation after usage of the character “thought balloon” or “rainbow” be fixed anyhow in examples like the following?

1. [Good](https://lkml.org/lkml/2017/11/7/599 "LKML: nfs/write: Use common error handling code in nfs_lock_and_join_requests()") or [check again](https://patchwork.kernel.org/patch/10047013/ "Patchwork: nfs/write: Use common error handling code in nfs_lock_and_join_requests()")
2. [Good](https://lkml.org/lkml/2017/11/7/486 "LKML: caif: Use common error handling code in cfdgml_receive()") or [check again](https://patchwork.kernel.org/patch/10046849/ "Patchwork: caif: Use common error handling code in cfdgml_receive()")
3. [Good](https://lkml.org/lkml/2017/11/5/65 "LKML: USB: core: Improve unlocking of a mutex in two functions") or [check again](https://patchwork.kernel.org/patch/10041689/ "Patchwork: USB: core: Improve unlocking of a mutex in two functions")

**Comment by ajdlinux** [comment]
Shows up fine on OzLabs Patchwork, which is far newer than kernel.org patchwork, so I assume this will be resolved when kernel.org eventually updates to Patchwork 2.0.

e.g. https://patchwork.ozlabs.org/patch/835301/

**Comment by daxtens** [comment]
This looks like it's fixed in 2.0 so I will close it. If it happens again let us know.
