### ISSUE TITLE
Add anchors to message sections

### ISSUE THREAD

**Issue by elfring** [getpatchwork/patchwork#141]
Comments which were added to a patch are displayed. I would appreciate then if [corresponding text parts will be marked with anchors](https://en.wikipedia.org/wiki/HTML_element#Anchor "Description for the usage of anchors in HTML") so that they can be used for unique links.
Which naming pattern will be appropriate for [these fragment identifiers](https://en.wikipedia.org/wiki/Fragment_identifier "Description for the usage of fragment identifiers")?

**Comment by ajdlinux** [comment]
This is already implemented.

**Comment by elfring** [comment]
It seems that I got a questionable view from patchwork instances on kernel.org (in comparison to the version “2.0.0.alpha-0” on ozlabs.org).

**Comment by stephenfin** [comment]
@elfring Aye, the instance on kernel.org is very old. This _is_ available in 2.0 but would not be available in that version.

**Comment by elfring** [comment]
With which version should corresponding software extensions become generally available then?

**Comment by stephenfin** [comment]
This was released in [2.0.0](http://patchwork.readthedocs.io/en/latest/releases/dazzle/#new-features).

**Comment by elfring** [comment]
* How can it be achieved that the permalink functionality can be used also with any more Patchwork installations?
* When will corresponding software updates be applied on other popular system instances?

**Comment by stephenfin** [comment]
@elfring That's entirely down to the admin of instance. You should email said individual(s) if you'd like them to update the instance/backport features like this.

**Comment by elfring** [comment]
Have you got any better contacts to the system administrators for kernel.org (than me for example)?

**Comment by stephenfin** [comment]
Afraid not. Per [the original announcement](https://lwn.net/Articles/313344/), it would seem ftpadmin@kernel.org is the place to go, though webmaster@kernel.org might also be a good shout.

**Comment by elfring** [comment]
>Afraid not.

This is a pity.

* Are you working with any system administrators together for the improvement of desired software performance?
* Are special users waiting for the general availability of another software release?

**Comment by daxtens** [comment]
We're just developing patchwork. We do try to cooperate with the sysadmins
- we take their bug reports very seriously, for example! But that's about
as far as it goes. I think kernel.org is waiting for us to squish some
performance issues before upgrading, but I'm not really sure - as Stephen
said, you'd need to ask them.

Regards,
Daniel

**Comment by elfring** [comment]
>… you'd need to ask them.

I got a response yesterday.

**Comment by stephenfin** [comment]
Good to hear. Positive stuff, I hope?

**Comment by elfring** [comment]
>Positive stuff, I hope?

I assume that some details can be improved also in this software so that a switch to a newer version will become more appealing (especially together with scalability concerns).
