### ISSUE TITLE
Ability to add tags that don't also have a column in the UI

### ISSUE THREAD

**Issue by mpe** [getpatchwork/patchwork#142]
Currently when a tag is added it results in a column appearing in the UI.

This is good for common tags, but there is a long tail of tags that would be nice to add, so that they're recognised by patchwork, but not added to the UI.

Bascially a bool on the Tag model which specifies if it should also be shown in the UI would be sufficient I think.

**Comment by stephenfin** [comment]
Yup. I think this is a good idea. FYI, how we extract tags from patches for use in mboxes and how we display them in the web UI are completely separate things. This would help close that gap.

**Comment by ajdlinux** [comment]
Sent patch
