### ISSUE TITLE
allow change of username

### ISSUE THREAD

**Issue by ajdlinux** [getpatchwork/patchwork#149]
Someone on the Patchwork mailing list asked about changing usernames. Maybe we should allow this.

**Comment by stephenfin** [comment]
I'd swear I had this tracked somewhere but clearly not. I think that, when I last checked, this is supported by `django.contrib.auth`: it's simply a case of wiring it up into our views.

**Comment by ajdlinux** [comment]
Looks like you might have been tracking it at https://github.com/getpatchwork/patchwork/issues/50

**Comment by ajdlinux** [comment]
Duplicate of #50
