### ISSUE TITLE
Regrouping for patches

### ISSUE THREAD

**Issue by elfring** [getpatchwork/patchwork#162]
Change and patch granularity is a general development topic. It can happen then that a software maintainer finds a specific adjustment too small (especially when similar changes occur in significant numbers) for an area. The desire evolves to recombine (or regroup) possible update steps to more pleasing patches.

Can this issue tracking tool help with better change management there?

**Comment by stephenfin** [comment]
I'm also confused by this one. Are you suggesting that you want the maintainer to be able to rework (combine, split) patches via Patchwork? If so, I don't think we're going to support that. If changes are required, then new patches should be requested from the submitter, or the maintainer should make the changes before applying the patch.

**Comment by elfring** [comment]
>Are you suggesting that you want the maintainer to be able to rework (combine, split) patches via Patchwork?

Yes. - I propose to support additional actions besides “simple” rejections.


>If changes are required, then new patches should be requested from the submitter,

This is one possibility.


>or the maintainer should make the changes before applying the patch.

Another possibility could be to regroup update steps if such a change recombination will still work.

**Comment by stephenfin** [comment]
Ah, then I'm afraid that's out of scope. Patchwork is designed to [supplement mailing lists, not replace them](http://patchwork.readthedocs.io/en/latest/usage/design/#patchwork-should-supplement-mailing-lists-not-replace-them). If you're looking for things like interactive editing, Gerrit, GitHub, GitLab et al are more than adequate solutions.

**Comment by elfring** [comment]
Your software documentation contains the following information.

“…
However, a future development item for Patchwork is to facilitate on-list commenting, by providing a “send a reply to the list” feature for logged-in users.
…”


A reply could inform involved contributors that an other change combination would be applied instead of a proposed patch series.
Such software design decisions happened on the Linux mailing list for example.
