### ISSUE TITLE
improved workflow management

### ISSUE THREAD

**Issue by elfring** [getpatchwork/patchwork#163]
* Do you support the existing standards in [this application area](https://en.wikipedia.org/wiki/Workflow "Description for the usage of workflows")?
* How much do you apply [workflow modelling patterns](http://www.workflowpatterns.com/patterns/ "Patterns around workflows")?

**Comment by stephenfin** [comment]
I've no idea what this mean. What's the ask here?

**Comment by elfring** [comment]
Do you know any [workflow management standards](https://en.wikipedia.org/wiki/Workflow_management_system#International_standards "Standards for workflow management") and corresponding collaboration possibilities?

**Comment by stephenfin** [comment]
I'm afraid I do not. How does this affect Patchwork?

**Comment by elfring** [comment]
[Events](https://patchwork.readthedocs.io/en/latest/usage/overview/#events "Description for events") are supported by this patch tracking system. I imagine that corresponding information can be forwarded to [a known workflow engine](https://en.wikipedia.org/wiki/Workflow_engine "Description for workflow engines") (for example).

**Comment by stephenfin** [comment]
OK, but why would you want to do this. Can you consider me a complete newb and explain what a workflow engine does and why we'd want to forward things from Patchwork to that? Do you personally have a use case for this?

**Comment by elfring** [comment]
>OK, but why would you want to do this.

I would appreciate if a few kinds of change resistance could be adjusted somehow.


>Can you consider me a complete newb

I would prefer to treat you as a more knowledgable software developer.


>and explain what a workflow engine does

Other information sources provide sufficient descriptions already.


>and why we'd want to forward things from Patchwork to that?

This software supports some extra data processing for patches to some degree. There will be functionality handled by additional existing software components (and corresponding services).


>Do you personally have a use case for this?

Yes. - I am contributing to various free software. Patches can eventually trigger special management actions there.

**Comment by elfring** [comment]
>…, but this sounds a little insulting.

It seems that you interpreted my response in unwanted directions.

How much do you care for [special management actions](https://patchwork.readthedocs.io/en/latest/usage/delegation/ "Using autodelegation?")?

**Comment by daxtens** [comment]
I have worked on a workflow engine before. I would like the whole concept kept separate from patchwork for a number of reasons. I agree with Stephen that this is wontfix.

The only way I could see this being integrated with patchwork is through the API - a separate service can consume the API and do whatever workflow management you desire. If there are specific API things you need to do that, please open a new bug for that. You can look at Snowpatch for an example of using the API to integrate with another service.
