### ISSUE TITLE
target_url of a Check should be optional

### ISSUE THREAD

**Issue by ruscur** [getpatchwork/patchwork#164]
When submitting a Check on a patch, a target URL is required for details of that test.  For some checks this isn't needed, for example, a simple check that just says the patch successfully applied to a branch.  So this field should be nullable.

**Comment by stephenfin** [comment]
Yeah, this sounds fair. Would be a good call for 2.2.

**Comment by stephenfin** [comment]
@ruscur actually, this isn't enforced in the model and doesn't appear to be enforced in the REST API. Where were you seeing this issue?

**Comment by stephenfin** [comment]
Yeah, this must refer to the XML-RPC API.

https://github.com/getpatchwork/patchwork/blob/9d2d7c1ca7765cff9865292fc0f4382509c47ff0/patchwork/views/xmlrpc.py#L902-L904

While we could fix this, this API is considered deprecated now so we should really only be fixing critical bugs. I'm going to close this as a WONTFIX, but please re-open if you disagree.

**Comment by ruscur** [comment]
Yeah this must have been my mistake, I was referring to the REST API but it's possible (and probably quite likely) that I was doing something else wrong in my check parameters and got confused.  My bad.
