### ISSUE TITLE
parsemail managment command: exit 1 on genuine errors

### ISSUE THREAD

**Issue by daxtens** [getpatchwork/patchwork#171]
@jk-ozlabs reports that it would be much easier to debug at scale if the parsemail managment command exits 0 on "expected" failures - non-patch mail and X-P-H: ignore, but returns 1 if there's a genuine system error. Then postfix's tempfail system could be used to hold mail and give us a window to fix the bug before losing the patch.

**Comment by jk-ozlabs** [comment]
This isn't just for debugging - it's for correctly integrating into a local MDA.

If the parsemail management command can't distinguish actual failures (eg, a connection problem to the db) from expected cases (no patch in an email), I have no way to know when to tempfail a delivery to the parsemail script. That means I have no option but to drop failed parses.
