### ISSUE TITLE
pwclient should report more user-friendly message on Connection Refused

### ISSUE THREAD

**Issue by daxtens** [getpatchwork/patchwork#172]
From an email exchange, pwclient failed with:

>> [long traceback snipped]
>> socket.error: [Errno 111] Connection refused
>
> This looks like what would happen if you tried to use pwclient when our
> web server was down.  This happens every now and then for very short
> periods of time when we do updates to various things (including
> libraries that the web server itself depends on).
>
> Do the developers:  maybe it is worth catching this error in particular
> and giving some reasonable message (or, optionally,trying again after a
> short wait - or both).

Do this in the pwclient rest api rewrite.

**Comment by stephenfin** [comment]
Moved to https://github.com/getpatchwork/pwclient/issues/4
