### ISSUE TITLE
Add searching for patches

### ISSUE THREAD

**Issue by mellowcandle** [getpatchwork/patchwork#185]
Allow searching by text or by Author.

**Comment by mellowcandle** [comment]
I was referring to the web ui. It think it will be a great addition.

**Comment by fronchetti** [comment]
This issue was already fixed. Version version v2.1.0.post176-g27f9e7a contains the search system.

**Comment by ajdlinux** [comment]
@daxtens @stephenfin does this still need fixing?

**Comment by stephenfin** [comment]
Yeah, this has actually been here for a long time. We don't support cross-project search but within a project, you have the ability to do both of these. Unless this issue referred to the ability to search *all* projects, I think this can actually be closed and that's what I'm going to do.

![image](https://user-images.githubusercontent.com/1690835/60718875-dcdf4b00-9f1d-11e9-8f43-5a6f13c81dab.png)

**Comment by ajdlinux** [comment]
I note that our search system can't do anything about the commit message or patch body, just the title. But doing something about that would be a lot of work for limited gain.

**Comment by stephenfin** [comment]
Correct. We'd probably need to introduce an actual search engine like Elasticsearch  assuming we wanted to support something other than exact match since full text search is so darn slow (in MySQL anyway). It hardly seems worth the effort when Google et al. can just do it for us
