### ISSUE TITLE
v2.0.3: Missing migration

### ISSUE THREAD

**Issue by charlemagnelasse** [getpatchwork/patchwork#192]
The `./manage.py migrate` shows me following:

    Operations to perform:
      Apply all migrations: admin, auth, authtoken, contenttypes, patchwork, sessions, sites
    Running migrations:
      No migrations to apply.
      Your models have changes that are not yet reflected in a migration, and so won't be applied.
      Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

`./manage.py makemigrations` creates a file called `patchwork/migrations/0020_auto_20180623_1904.py` with the content

    # -*- coding: utf-8 -*-
    # Generated by Django 1.10.7 on 2018-06-23 19:04
    from __future__ import unicode_literals
    
    from django.db import migrations
    
    
    class Migration(migrations.Migration):
    
        dependencies = [
            ('patchwork', '0019_userprofile_show_ids'),
        ]
    
        operations = [
            migrations.AlterModelOptions(
                name='patch',
                options={'base_manager_name': 'objects', 'verbose_name_plural': 'Patches'},
            ),
            migrations.AlterModelOptions(
                name='series',
                options={'ordering': ('date',), 'verbose_name_plural': 'Series'},
            ),
        ]

**Comment by stephenfin** [comment]
Thanks for picking this up. This was resolved in 2.1 but it's not possible to backport migrations. As none of these changes are strictly necessary, I've just reverted them on `stable/2.0`. This will form part of a future `2.0.4` release. Also, sorry again for the delay.

**Comment by stephenfin** [comment]
Closed in https://github.com/getpatchwork/patchwork/commit/a2a51cb7777e054817fbac02458d0b65bd5e9146
