### ISSUE TITLE
UTF-8 author name corruption

### ISSUE THREAD

**Issue by torvalds** [getpatchwork/patchwork#194]
Apparently patchwork will corrupt author names, see for example

   https://patchwork.kernel.org/patch/10431971/

which caused the author name to be reported as '???' in the kernel logs. 

I can see the original email in my own mail queue, and it has

    From:   =?big5?B?ufmxUrph?= <kt.liao@emc.com.tw>

in the headers, but patchwork has corrupted it to ??? not just in the web view, but also in the downloaded mbox file.

Please fix. We try very hard to accomodate non-US-ASCII names these days. That may not always have been the case, but utf-8 is a thing today. The only valid thing, in fact.

**Comment by torvalds** [comment]
It looks like this may already be fixed in a newer version of patchwork.

Because when looking at

  https://lore.kernel.org/patchwork/patch/909790/

the Chinese characters show up correctly.

**Comment by ajdlinux** [comment]
You're not the first to notice this: the report at https://patchwork.ozlabs.org/patch/430569/ dates from January 2015. kernel.org patchwork is so ancient it doesn't even print a version number in the footer.

Now that we've had some time to iron out the performance issues in patchwork 2.0 it's probably time for patchwork.kernel.org to get an upgrade to 2.1...

**Comment by stephenfin** [comment]
> You're not the first to notice this: the report at patchwork.ozlabs.org/patch/430569 dates from January 2015. kernel.org patchwork is so ancient it doesn't even print a version number in the footer.
> 
> Now that we've had some time to iron out the performance issues in patchwork 2.0 it's probably time for patchwork.kernel.org to get an upgrade to 2.1...

Yup, this has been resolved since at least 1.0, iirc, though no single change jumped out at me as I looked through the logs.

At noted above, that version of patchwork is ancient and really needs to be updated to something a newer. Feel free to send people this way (or the [the list](mailto:patchwork@lists.ozlabs.org) if help is needed in doing so.

**Comment by stephenfin** [comment]
(I was pretty sure [patchwork.kernel.org was being superseded by lore.kernel.org/patchwork too](https://www.kernel.org/lore.html). Maybe things have changed?)

**Comment by ajdlinux** [comment]
@stephenfin According to the page you linked, only the LKML project on pw.k.o is being deprecated - which makes sense given the other subsystem lists that are hosted on the k.o instance.

**Comment by stephenfin** [comment]
@ajdlinux Ah, correct. My mistake.
