### ISSUE TITLE
Colour patch row based on check status

### ISSUE THREAD

**Issue by mpe** [getpatchwork/patchwork#198]
The ability to attach test results to a patch using the check feature is awesome.

However the display of the results in the list view is *very* subtle. ie. a failed patch and a successfully checked patch differ only by the position of a single digit in the S/W/F column, they're easy to miss.

What would be nice is if the row was coloured based on the status.

So perhaps fail: red, warning: orange, success: white or green.

Green for successful checks would be good, as it would mean you could skip over patches that hadn't been checked yet, but it might make the UI a bit garish.

Here is a terribly gimped screenshot of what I have in mind:

![patchwork-checks](https://user-images.githubusercontent.com/54119/42981295-cd97888c-8c1e-11e8-83d9-14526920dba1.png)

**Comment by ruscur** [comment]
Thoughts on the way that patchwork.freedesktop.org handles it?

https://patchwork.freedesktop.org/project/intel-gfx/series/?ordering=-last_updated

I would personally only want the coloured background behind the S/W/F part

**Comment by ajdlinux** [comment]
Good idea but like @ruscur I think colouring the whole row might be a bit much, very visually noisy. I like the look of pw.fdo (though it annoys me that their s/w/f blocks aren't of equal width)

**Comment by stewart-ibm** [comment]
Maybe red for 0 in A/R/T too, to provide extra incentive for maintainers to not merge unreviewed code?

**Comment by mpe** [comment]
Yep agree the FDO UI is nicer than my idea. Can we just pull in their code?

**Comment by ruscur** [comment]
I really want this so I might try and do it myself if noone else wants to, note that I know nothing about frontend webdev so making a thing red or green may take several eons

**Comment by tmonjalo** [comment]
The colors have been added on check numbers:
https://github.com/getpatchwork/patchwork/commit/974ff0c9959db
It is less noisy than coloring the whole row.
I think this issue can be closed.
