### ISSUE TITLE
update incorrect FSF addresses 

### ISSUE THREAD

**Issue by pavlinamv** [getpatchwork/patchwork#210]
Some of the files contain incorrect (old) address to FSF in the license terms:

/var/lib/patchwork/patchwork/__init__.py
/var/lib/patchwork/patchwork/admin.py
/var/lib/patchwork/patchwork/api/base.py
/var/lib/patchwork/patchwork/api/bundle.py
/var/lib/patchwork/patchwork/api/check.py
/var/lib/patchwork/patchwork/api/comment.py
/var/lib/patchwork/patchwork/api/cover.py
/var/lib/patchwork/patchwork/api/embedded.py
/var/lib/patchwork/patchwork/api/event.py
/var/lib/patchwork/patchwork/api/filters.py
/var/lib/patchwork/patchwork/api/index.py
/var/lib/patchwork/patchwork/api/patch.py
/var/lib/patchwork/patchwork/api/person.py
/var/lib/patchwork/patchwork/api/project.py
/var/lib/patchwork/patchwork/api/series.py
/var/lib/patchwork/patchwork/api/user.py
/var/lib/patchwork/patchwork/apps.py
/var/lib/patchwork/patchwork/bin/parsemail-batch.sh
/var/lib/patchwork/patchwork/bin/parsemail.sh
/var/lib/patchwork/patchwork/bin/pwclient
/var/lib/patchwork/patchwork/compat.py
/var/lib/patchwork/patchwork/context_processors.py
/var/lib/patchwork/patchwork/fields.py
/var/lib/patchwork/patchwork/filters.py
/var/lib/patchwork/patchwork/forms.py
/var/lib/patchwork/patchwork/hasher.py
/var/lib/patchwork/patchwork/management/commands/cron.py
/var/lib/patchwork/patchwork/management/commands/parsearchive.py
/var/lib/patchwork/patchwork/management/commands/parsemail.py
/var/lib/patchwork/patchwork/management/commands/rehash.py
/var/lib/patchwork/patchwork/management/commands/retag.py
/var/lib/patchwork/patchwork/models.py
/var/lib/patchwork/patchwork/notifications.py
/var/lib/patchwork/patchwork/paginator.py
/var/lib/patchwork/patchwork/parser.py
/var/lib/patchwork/patchwork/signals.py
/var/lib/patchwork/patchwork/templatetags/listurl.py
/var/lib/patchwork/patchwork/templatetags/patch.py
/var/lib/patchwork/patchwork/templatetags/person.py
/var/lib/patchwork/patchwork/templatetags/project.py
/var/lib/patchwork/patchwork/templatetags/syntax.py
/var/lib/patchwork/patchwork/tests/__init__.py
/var/lib/patchwork/patchwork/tests/api/test_bundle.py
/var/lib/patchwork/patchwork/tests/api/test_check.py
/var/lib/patchwork/patchwork/tests/api/test_comment.py
/var/lib/patchwork/patchwork/tests/api/test_cover.py
/var/lib/patchwork/patchwork/tests/api/test_patch.py
/var/lib/patchwork/patchwork/tests/api/test_person.py
/var/lib/patchwork/patchwork/tests/api/test_project.py
/var/lib/patchwork/patchwork/tests/api/test_series.py
/var/lib/patchwork/patchwork/tests/api/test_user.py
/var/lib/patchwork/patchwork/tests/test_about.py
/var/lib/patchwork/patchwork/tests/test_bundles.py
/var/lib/patchwork/patchwork/tests/test_checks.py
/var/lib/patchwork/patchwork/tests/test_completion.py
/var/lib/patchwork/patchwork/tests/test_confirm.py
/var/lib/patchwork/patchwork/tests/test_detail.py
/var/lib/patchwork/patchwork/tests/test_encodings.py
/var/lib/patchwork/patchwork/tests/test_events.py
/var/lib/patchwork/patchwork/tests/test_expiry.py
/var/lib/patchwork/patchwork/tests/test_fields.py
/var/lib/patchwork/patchwork/tests/test_filters.py
/var/lib/patchwork/patchwork/tests/test_list.py
/var/lib/patchwork/patchwork/tests/test_mail_settings.py
/var/lib/patchwork/patchwork/tests/test_management.py
/var/lib/patchwork/patchwork/tests/test_mboxviews.py
/var/lib/patchwork/patchwork/tests/test_notifications.py
/var/lib/patchwork/patchwork/tests/test_paginator.py
/var/lib/patchwork/patchwork/tests/test_parser.py
/var/lib/patchwork/patchwork/tests/test_projects.py
/var/lib/patchwork/patchwork/tests/test_registration.py
/var/lib/patchwork/patchwork/tests/test_series.py
/var/lib/patchwork/patchwork/tests/test_tags.py
/var/lib/patchwork/patchwork/tests/test_updates.py
/var/lib/patchwork/patchwork/tests/test_user.py
/var/lib/patchwork/patchwork/tests/test_xmlrpc.py
/var/lib/patchwork/patchwork/tests/utils.py
/var/lib/patchwork/patchwork/urls.py
/var/lib/patchwork/patchwork/version.py
/var/lib/patchwork/patchwork/views/__init__.py
/var/lib/patchwork/patchwork/views/about.py
/var/lib/patchwork/patchwork/views/api.py
/var/lib/patchwork/patchwork/views/bundle.py
/var/lib/patchwork/patchwork/views/comment.py
/var/lib/patchwork/patchwork/views/cover.py
/var/lib/patchwork/patchwork/views/mail.py
/var/lib/patchwork/patchwork/views/notification.py
/var/lib/patchwork/patchwork/views/patch.py
/var/lib/patchwork/patchwork/views/project.py
/var/lib/patchwork/patchwork/views/pwclient.py
/var/lib/patchwork/patchwork/views/series.py
/var/lib/patchwork/patchwork/views/user.py
/var/lib/patchwork/patchwork/views/utils.py
/var/lib/patchwork/patchwork/views/xmlrpc.py
/var/lib/patchwork/patchwork/wsgi.py
/var/lib/patchwork/tools/patchwork-update-commits
/var/lib/patchwork/tools/post-receive.hook

Old address:

    Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

Should be:
Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335 USA

Best regards
Pavlina Moravcova Varekova

**Comment by stephenfin** [comment]
Noted [here](https://www.fsf.org/news/fsf-moving.html) and [here](https://www.fsf.org/news/fsf-responds-to-linuxworld-in-boston). Correct address seen [here](https://www.fsf.org/about/contact/).

**Comment by daxtens** [comment]
We should just delete the address, I think anyone who wants to know can
google it. That's what the kernel does, for example.

Regards,
Daniel
