### ISSUE TITLE
--limit=1000 --submitter 'First Last' doesn't show new patches

### ISSUE THREAD

**Issue by andy-shev** [getpatchwork/patchwork#229]
Server: patchwork.ozlabs.org
API: 1.0
Project: linux-gpio
Submitter: Wolfram Sang

The execution of `git pw patch list --submitter 'Wolfram Sang'` shows at the top something like:

    | 857404 | 10 months ago | [2/2] Documentation: gpio: correct return value of gpiod_get_direction   | Wolfram Sang (wsa@the-dreams.de) | new     | no         |            |
    | 857403 | 10 months ago | [1/2] gpio: correct docs about return value of gpiod_get_direction       | Wolfram Sang (wsa@the-dreams.de) | new     | no         |            |
    | 821362 | a year ago    | pinctrl: sh-pfc: r8a7795: add I2C pin support                            | Wolfram Sang (wsa@the-dreams.de) | new     | no         |            |

Any parameter to `--limit` doesn't affect this.

Now, if I do execute `git pw patch list --limit=1000` (no `--submitter` provided) and list far enough:

    | 990015 | 8 days ago   | [2/2] pinctrl: sh-pfc: r8a7794: initialize TDSEL register                | Wolfram Sang (wsa+renesas@sang-engineering.com)          | new     | no         |            |
    | 990014 | 8 days ago   | [1/2] pinctrl: sh-pfc: r8a7790: initialize TDSEL register                | Wolfram Sang (wsa+renesas@sang-engineering.com)          | new     | no         |            |

and so on (he is active maintainer and contributor to the mentioned project.

Web output:
https://patchwork.ozlabs.org/project/linux-gpio/list/?submitter=69646&order=-date&archive=both&state=*

**Comment by andy-shev** [comment]
Just noticed it might be related to `+` in the e-mail which is rightfully can be there.

**Comment by stephenfin** [comment]
As noted in https://github.com/getpatchwork/git-pw/issues/27#issuecomment-436811637, this is a known issue with API v1.0. We just need to wait for ozlabs to update to Patchwork 2.1, unfortunately.
