### ISSUE TITLE
Pull request emails with line break drops branch/tag

### ISSUE THREAD

**Issue by olofj** [getpatchwork/patchwork#233]
If someone does copy/paste of a git pull request it is pretty common that the request is broken up on several lines with the tag/branch on a new line. Patchwork drops the second component based on current regexps.

Example email: https://lore.kernel.org/linux-arm-kernel/d131fdd3-663c-9a5b-4296-94f2635f8c41@gmail.com/raw

Gets misparsed: https://patchwork.kernel.org/patch/10699511/

Setting up test environment is more work than I'm looking to do right now just to test a script change, so this is a completely untested patch for this:

```
diff --git a/patchwork/parser.py b/patchwork/parser.py
index d6fa843..b0a0f5b 100644
--- a/patchwork/parser.py
+++ b/patchwork/parser.py
@@ -869,6 +869,15 @@ def parse_patch(content):
 def parse_pull_request(content):
     git_re = re.compile(r'^The following changes since commit.*'
                         r'^are available in the git repository at:\n'
+                        r'^\s*(\S+\s+\S+)\s*'
+                        r'for you to fetch changes up to.*',
+                        re.DOTALL | re.MULTILINE | re.IGNORECASE)
+    match = git_re.search(content)
+    if match:
+        return match.group(1)
+
+    git_re = re.compile(r'^The following changes since commit.*'
+                        r'^are available in the git repository at:\n'
                         r'^\s*([\S]+://[^\n]+)$',
                         re.DOTALL | re.MULTILINE | re.IGNORECASE)
     match = git_re.search(content)
```

**Comment by ajdlinux** [comment]
https://patchwork.ozlabs.org/patch/1196150/ thanks to @mricon

**Comment by ajdlinux** [comment]
Should be fixed by https://github.com/getpatchwork/patchwork/commit/8c229caa71d58e971708ac7ebdb02d6858cd2a4c
