### ISSUE TITLE
Parsing of patches in series are racy

### ISSUE THREAD

**Issue by pevik** [getpatchwork/patchwork#241]
Any idea why series name sometimes get lost? In some patchsets one of the
patches has "Untitled series #N" title, e.g. patch [1] being lost from [2].

[1] https://patchwork.ozlabs.org/patch/1021139/
[2] https://patchwork.ozlabs.org/project/ltp/list/?series=84657&state=*

**Comment by daxtens** [comment]
I haven't checked with the list archives, but I think I had pinned that on
race conditions: you can end up parsing 2 messages simultaneously. We have
hardened the parser so that it doesn't completely blow up and lose mail in
that case, we haven't got a chance to go back and make series parsing
reliable.

>

**Comment by pevik** [comment]
Thanks for info. That's certainly better than loosing mail.

**Comment by alialnu** [comment]
We have the same issue on patches.dpdk.org, here is an example:

https://patches.dpdk.org/project/dpdk/list/?series=2811&archive=both&state=*
https://patches.dpdk.org/project/dpdk/list/?series=2812&archive=both&state=*

I tried reproducing manually multiple times, but wasn't able to. Please let me know if you can reproduce a case, it would certainly help with debugging.

@tmonjalo

**Comment by daxtens** [comment]
To reproduce this you need parallel parsing: see http://patchwork.ozlabs.org/patch/1179321/

**Comment by mricon** [comment]
It would appear to still be happening with 2.2.2. Here's the series:

https://patchwork.kernel.org/project/netdevbpf/list/?series=383955

and here are 2 patches that are not matched to the series:

https://patchwork.kernel.org/project/netdevbpf/list/?series=383959
https://patchwork.kernel.org/project/netdevbpf/list/?series=383961

I can see from the logs that they were fed to parsemail in consecutive order with the rest of the series, so whatever is causing the series lookup to fail, I don't think it's related to parallel processing. I do note that there's another series created in-between 383955 and 383959 (increments go at +2). However, this doesn't prevent other patches in that series from being properly allocated.

Curious.

**Comment by kuba-moo** [comment]
In fact subjectively (switching from ozlabs to kernel.org) it feels a lot worse in 2.2.2 (ozlabs is on 2.2.0).
Here is more examples:
https://patchwork.kernel.org/project/netdevbpf/list/?series=383539
https://patchwork.kernel.org/project/netdevbpf/list/?series=383037
https://patchwork.kernel.org/project/netdevbpf/list/?series=382879
https://patchwork.kernel.org/project/netdevbpf/list/?series=382623
These are just from last 2 days.

**Comment by mricon** [comment]
FYI, I fixed it by ensuring that we *always* feed patchwork one patch at a time.

**Comment by alialnu** [comment]
> 
> 
> FYI, I fixed it by ensuring that we _always_ feed patchwork one patch at a time.

Can you share more information about how you did that if it's possible? Was it an MTA setting? Or maybe feed emails to a local script that uses a lockfile first before passing them to Patchwork?

**Comment by mricon** [comment]
Yes, we're passing everything through procmail and waiting on parsemail to return before moving on to the next message.
