### ISSUE TITLE
Django 1.10 Support

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/patchwork#26]
# Overview

Django 1.10 is almost complete. We should support it, in addition to the existing versions of Django (currently 1.6 - 1.8, and soon 1.9).

# Dependencies

Django 1.9 support (#25) must be added first.

# Additional Work Items

Like any refactoring, we can take this opportunity to clean up some less pretty aspects of the code base.

# Alternatives

None.

# Useful resources

* [**Django 1.10 Preliminary Release Notes**](https://docs.djangoproject.com/en/dev/releases/1.10/)

**Comment by daxtens** [comment]
I have some patches in progress for this.

It seems we simply need to do the following:
 - Bump django-rest-framework to 3.4. This requires disabling it for Django 1.7.
 - remove 'load cycle from future' in a template.
 - convert:
```
-        return qs.select_related('user__username')
+        return qs.prefetch_related('user')
```

I'll get the patches out at some point.

**Comment by stephenfin** [comment]
I also have this done (it's waiting on the management command patches to merge). Whoever gets them up first :)
