### ISSUE TITLE
Influence the display for the maximum number of search results

### ISSUE THREAD

**Issue by elfring** [getpatchwork/patchwork#312]
Searches are supported by this software.
The number of presented search results can be limited on a web page.
I would occasionally like to increase the corresponding maximum.
Can the row count be specified by an URL parameter?

**Comment by stephenfin** [comment]
Are you referring to the web UI or the REST API?

**Comment by elfring** [comment]
I see configuration possibilities for both user interfaces.

**Comment by stephenfin** [comment]
For the REST API, you want `per_page`. I'm not sure what the option for the Web UI is though.

**Comment by elfring** [comment]
How can desired search configuration parameters be found for the web user interface?

**Comment by stephenfin** [comment]
Looking at https://github.com/getpatchwork/patchwork/blob/master/patchwork/paginator.py it seems you can't do this via a web parameter but you can override the default in your user profile.

**Comment by elfring** [comment]
Can the user property become available as a query parameter?

**Comment by stephenfin** [comment]
It could, but is there a significant advantage?

**Comment by elfring** [comment]
I imagine that a different row count selection can occasionally matter for specific queries while user profiles should be kept unchanged.

**Comment by elfring** [comment]
What is still unclear for the presented use case?

**Comment by stephenfin** [comment]
You originally asked:

> Searches are supported by this software.
> The number of presented search results can be limited on a web page.
> I would occasionally like to increase the corresponding maximum.
> Can the row count be specified by an URL parameter?

I've noted that there is a way to do this via user settings and that you can rely on the REST API if you need something more complete. "I want to be able to increase the amount of items shown on a page" is a good use case and is something we already support via user settings.

> I imagine that a different row count selection can occasionally matter for specific queries while user profiles should be kept unchanged.

This, on the other hand, is a nice-to-have rather than a must-have, since there are valid alternatives. This means it's unlikely that I'll work on this so closing the issue is the correct thing to do. If this really matters to you, please do submit a patch.

**Comment by elfring** [comment]
Are there any restrictions taken into account for the maximum of items shown on a page by the (REST) API?

**Comment by stephenfin** [comment]
Yes. There is a limit of 100 items per page on most endpoints. This is noted in the [docs](https://patchwork.readthedocs.io/en/latest/api/rest/#pagination).

**Comment by elfring** [comment]
Can the custom page size selection depend on user permissions?
(Should the value occasionally be below an upper limit?)

**Comment by stephenfin** [comment]
No. It's site-specific, not user-specific.
