### ISSUE TITLE
Add API for adding patches to bundles

### ISSUE THREAD

**Issue by kuba-moo** [getpatchwork/patchwork#316]
Hi!

There seems to be no API right now to add patches to bundles. It'd be extremely useful - for Linux networking maintainership (netdev) we collect stable patches into a bundle. Today it's the only thing which requires a context switch into the Web UI when applying a patch.

**Comment by daxtens** [comment]
Good news, there's a patch set on the list for this. Once we land that we'll cut Patchwork 2.2 and then once ozlabs upgrades (and `git pw` learns about it) everything should just work.

**Comment by kuba-moo** [comment]
Awesome, can't wait :)

**Comment by stephenfin** [comment]
FYI, `git-pw` 1.9.0 exposes this functionality via a couple of new commands.

- `git pw bundle create`
- `git pw bundle update`
- `git pw bundle delete`
- `git pw bundle add`
- `git pw bundle remove`

More information is available [here](https://patchwork.readthedocs.io/projects/git-pw/en/latest/release-notes/#relnotes-1-9-0)
