### ISSUE TITLE
Displaying patch rejections

### ISSUE THREAD

**Issue by elfring** [getpatchwork/patchwork#317]
Counters can be displayed for three tags below the column header “A/R/T”.
:crystal_ball: How do you think about to present the information how often patches got rejected?

**Comment by stephenfin** [comment]
We already track this via patch states, no?

**Comment by elfring** [comment]
The patch status represents a specific kind of information, doesn't it?
But I am looking for a clear representation of positive and negative code review feedback together.
:crystal_ball: Will additional software development reports and statistic displays become helpful?

**Comment by daxtens** [comment]
I'm not sure that outright patch rejections are particularly common - I see
almost none in my work as a kernel developer. When I do see them, they
don't tend to follow a standard format - unlike Acked-by or Tested-by etc.
So I don't think that this would add value in the current kernel workflow.
If there's another project that would benefit from it, I'd be happy to hear
from them.

**Comment by elfring** [comment]
>I'm not sure that outright patch rejections are particularly common

I got other impressions for my selection of possible software adjustments.


>When I do see them, they don't tend to follow a standard format

There are variations to consider how other contributors occasionally express their disagreements (if you get such a negative feedback at all).


>So I don't think that this would add value in the current kernel workflow.

I suggest to reconsider this view.

**Comment by stephenfin** [comment]
Can you provide some examples of the kinds of thing you'd like to capture?

**Comment by elfring** [comment]
>When I do see them, they don't tend to follow a standard format - unlike …

I suggest to take another analysis possibility better into account.
How do you think about to show patch review with messages which do not contain such known tags?

-----

>Can you provide some examples of the kinds of thing you'd like to capture?

Would you like to check the occurrence of a key word like “NACK” in feedback?

**Comment by daxtens** [comment]
Hi Markus,

I don't think this is a direction we want to take at the moment, so I'm
going to close this now. However, I'm happy to reconsider if you can send
patches implementing this to the mailing list.

Kind regards
Daniel
