### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by Belee05** [getpatchwork/patchwork#338]
![Uploading image.png…]()

```
Starting patchwork_db_1 ... done
Starting patchwork_web_1 ... done
Attaching to patchwork_db_1, patchwork_web_1
db_1   | 2020-02-29 04:29:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian9 started.
web_1  | The patchwork directory doesn't seem to be mounted!
web_1  |
web_1  | Are you using docker-compose? If so, you may need to create an SELinux rule.
web_1  | Refer to the development installation documentation for more information.
web_1  | If not, you need -v PATH_TO_PATCHWORK:/home/patchwork/patchwork
db_1   | find: '/var/lib/mysql/': Permission denied
db_1   | chown: changing ownership of '/var/lib/mysql/': Permission denied
patchwork_db_1 exited with code 1
patchwork_web_1 exited with code 1
```

**Comment by stephenfin** [comment]
The database container mounts that directory at `tools/db/data`. If you change permissions for the parent directory, `tools/db`, that should resolve this.

**Comment by Belee05** [comment]
![image](https://user-images.githubusercontent.com/51012725/75607360-43f6e300-5b31-11ea-82eb-5025ad19405a.png)
pip install -r requirements-dev.txt

> The database container mounts that directory at `tools/docker/db/data`. If you change permissions for the parent directory, `tools/docker/db`, that should resolve this.
> 
> ```
> chmod 777 tools/docker/db
> ```
> 
> If you can't do this, I suggest you move the entire patchwork directory somewhere where this is possible. Alternatively, use the sqlite backend and forget docker entirely:
> 
> ```
> virtualenv .venv
> source .venv/bin/activate
> pip install -R requirements-dev.txt
> PW_DB_TYPE=sqlite DJANGO_SETTINGS_MODULE=patchwork.settings.dev python manage.py ...
> ```
![image](https://user-images.githubusercontent.com/51012725/75607378-70aafa80-5b31-11ea-9f08-6674967c7806.png)
pip install -r requirements-dev.txt

**Comment by stephenfin** [comment]
You need to install `libmysqlclient-dev` and `libpq-dev` on the host.

**Comment by stephenfin** [comment]
I assume you got this working.
