### ISSUE TITLE
The "bundles" button shouldn't require sign in

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/patchwork#34]
I could be mistaken, but clicking the bundles button in the menu bar should not necessarily redirect me to the login page. There are public bundles and these should be listed. If not public, then nothing should be listed **but** the redirect should not take place.

**Comment by stephenfin** [comment]
I was mistaken. The bundles button is used to list bundles assigned to the current user which, ostensibly enough, requires you to be signed it. "Public" bundles are public in that you can share links to the bundle with other people. Anonymous users can can use these links to see, but not edit, the list of patches in the bundle, while authenticated users can view and edit them. This should probably be documented, but I'm closing this particular bug as invalid.

**Comment by wangliu-iscas** [comment]
This bug reappeared in version 3.1.0. Click the "bundles" button, and you will jump to login.
This is the url :   https://patchwork.plctlab.org/user/login/?next=/project/gcc-patch/bundles/
