### ISSUE TITLE
Exclude "Series" from "Related"

### ISSUE THREAD

**Issue by rsarky** [getpatchwork/patchwork#344]
Recently in [this](https://github.com/getpatchwork/patchwork/commit/27c2acf56cd30e77c932a1dde87b6fc1de8eeb2c
) commit support for viewing related patches was introduced.

Related patches will always trivially contain the series a patch belongs to, so I think Patchwork should not include the patch's series under the patch's related patches.

**Comment by daxtens** [comment]
I'm not sure I understand you. Related patches have to be added via the API
or admin interface, and they don't automatically contain the series. The
series display is different than the related display. The series display
now looks like this:
[image: image.png]
and if you click expand
[image: image.png]

This patch has no related patches. If I add a (meaningless) related patch
the Related row appears:
[image: image.png]
and if you click show...
[image: image.png]

**Comment by daxtens** [comment]
I'm not sure I understand you. Related patches have to be added via the API
or admin interface, and they don't automatically contain the series. The
series display is different than the related display. The series display
now looks like this:
![image](https://user-images.githubusercontent.com/3307781/77040582-57002300-6a0c-11ea-8c0e-49692338d7de.png)


and if you click expand
![image](https://user-images.githubusercontent.com/3307781/77040592-5a93aa00-6a0c-11ea-8a4e-607fbabf9d7c.png)

This patch has no related patches. If I add a (meaningless) related patch
the Related row appears:

![image](https://user-images.githubusercontent.com/3307781/77040605-5ff0f480-6a0c-11ea-8689-2c43f642b811.png)

and if you click show...

![image](https://user-images.githubusercontent.com/3307781/77040621-65e6d580-6a0c-11ea-929f-4676c237ac14.png)

**Comment by rsarky** [comment]
Oh, I am sorry, my understanding about the related patches was incorrect.
Closing this.
Thanks!

**Comment by daxtens** [comment]
No worries, I hope you have a productive time with Patchwork.
