### ISSUE TITLE
Patch titles not parsed correctly from email subject prefixes?

### ISSUE THREAD

**Issue by ybakos** [getpatchwork/patchwork#36]
I may not know what I'm talking about, but it seems like Patchwork's email subject parsing is flawed? It seems like subject prefixes of emails are not consistently parsed. I've seen this in many Patchwork trackers, but here is a screenshot:
![screen shot 2016-04-06 at 4 21 42 pm](https://cloud.githubusercontent.com/assets/5502/14333357/ec4d42e6-fc13-11e5-848e-cb5cfd27c21a.png)

The subject prefixes are things like
* [PATCH reponame]
* [PATCH reponame vN]
* [PATCH reponame m/M]
* [PATCH reponame vN m/M]

So why do patch titles appear differently in Patchwork?

**Comment by stephenfin** [comment]
So this is done on purpose. These headers (`PATCH` and `reponame`) are useful in a mailing list, where patches can be intermingled with discussions and migrated from one list to another. However, on Patchwork this stuff would appear as unnecessary noise: all patches would have the same prefixes, after all. As a result, [we strip them out](https://github.com/getpatchwork/patchwork/blob/7bf4304821ab70bf4c86d7139e0c1a4753f6e5b8/patchwork/bin/parsemail.py#L318).

**Comment by ybakos** [comment]
Ah, there it is. Thanks for pointing it out in the source - I dug around but couldn't find it easily. Now it all makes sense. Thanks for all things Patchwork!
