### ISSUE TITLE
Parsearchive fails to handle case when patch is embedded inside a mail

### ISSUE THREAD

**Issue by rsarky** [getpatchwork/patchwork#369]
Refer [this](https://lore.kernel.org/linux-mm/20100104144332.96A2.A69D9226@jp.fujitsu.com/) email on lore.kernel.org.
Patchwork considers the entire email as a single patch which seems to be incorrect.

**Comment by daxtens** [comment]
I'm not quite sure what we should do. We don't want to go down the road of parsing embedded/attached emails, it's way too complex and error prone. Indeed if it were an attachment we would already ignore it.

People were more fast-and-loose with email practices in 2010, I think we can afford to be stricter in 2020.

**Comment by rsarky** [comment]
I agree. I could find around 20-30 such cases in a ~20k patches Patchwork instance. We can safely ignore this cases I presume then

**Comment by daxtens** [comment]
I think so.
