### ISSUE TITLE
patchwork misses some patches sent as replies

### ISSUE THREAD

**Issue by siddhesh** [getpatchwork/patchwork#389]
Example: https://patchwork.sourceware.org/project/glibc/patch/alpine.DEB.2.22.394.2012072340110.382403@digraph.polyomino.org.uk/#105372

That reply should have been parsed as a new patch (possibly superseding the previous patch) but instead it just posts it as a reply.

**Comment by daxtens** [comment]
I can't find a link to the actual patch in a mailing list archive - do you have a link?

If the mail begins with "Re:" it will never start a new patch, it will be a comment to an existing patch.

There is no logic at all to supersede an old version of a patch with a new version of a patch; that's entirely up to the project maintainers.

**Comment by siddhesh** [comment]
OK that explains it; it was indeed sent out with Re: https://sourceware.org/pipermail/libc-alpha/2020-December/120556.html

Would the project consider adding support to parse patches sent in reply, perhaps as an addon option?

**Comment by stephenfin** [comment]
I don't think that's wise. As it is, our parsing is incredibly complex and recognizing mails prefixed with `RE:` as replies is one of the few things we (think) we can rely on. Given how rare these corner cases are, I'd rather not support them, personally.

**Comment by ValZapod** [comment]
> If the mail begins with "Re:" it will never start a new patch, it will be a comment to an existing patch.

Yeah? Even if the the extension is .patch? Seriously? https://ffmpeg.org/pipermail/ffmpeg-devel/2021-June/280982.html
