### ISSUE TITLE
patchwork fails to parse patch with unicode text

### ISSUE THREAD

**Issue by siddhesh** [getpatchwork/patchwork#393]
The sourceware instance of patchwork (based on the stable 2.2 branch) fails to parse this patch posted on the list:

https://sourceware.org/pipermail/libc-alpha/2021-January/121972.html

It fails with the following trace:

```
Error when parsing incoming email: OperationalError(1366, "Incorrect string value: '\\xD0\\x92\\xD1\\x8B\\xD0\\xB4...' for column `patchwork`.`patchwork_patch`.`diff` at row 1")
Traceback (most recent call last):
  File "{redacted}/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "{redacted}/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "{redacted}/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "{redacted}/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "{redacted}/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1366, "Incorrect string value: '\\xD0\\x92\\xD1\\x8B\\xD0\\xB4...' for column `patchwork`.`patchwork_patch`.`diff` at row 1")
```

**Comment by daxtens** [comment]
Hmm interesting. It looks like the error is completely in mysql - I wonder
whether it is to blame or we are...

>

**Comment by stephenfin** [comment]
Looking at the [docs](https://docs.djangoproject.com/en/3.1/ref/unicode/#creating-the-database), it appears Django uses unicode for everything. This means your database needs to be configured for UTF-8 or UTF-16 data. I suspect your MySQL database is configured to use the [default `latin1` character set and `latin1_swedish_ci` collation](https://dev.mysql.com/doc/refman/5.7/en/charset.html). You need to change this. The Django docs helpfully provide [a link](https://dev.mysql.com/doc/refman/en/charset-database.html) with info on how to do this.

**Comment by stephenfin** [comment]
Closed as a docs bug since there's not much else we can do here.

**Comment by siddhesh** [comment]
To close the loop on this, it was indeed a database and table encoding issue.  I migrated them all to `utf8mb4` and it's been working well so far.
