### ISSUE TITLE
[v3] nonexistent relation in lib/sql/grant-all.postgres.sql

### ISSUE THREAD

**Issue by alialnu** [getpatchwork/patchwork#396]
```
$ psql -f lib/sql/grant-all.postgres.sql DATABASE_NAME

BEGIN
GRANT
psql:lib/sql/grant-all.postgres.sql:69: ERROR:  relation "patchwork_patchcomment_id_seq" does not exist
psql:lib/sql/grant-all.postgres.sql:80: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:86: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:93: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:101: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

The tables/sequences I have with pattern `patchwork_.*comment.*` are the following:
```
patchwork_comment_id_seq
patchwork_covercomment
patchwork_covercomment_id_seq
patchwork_patchcomment
```

**Comment by stephenfin** [comment]
Doh, thanks for the report. I really need to find a way to automate testing of these scripts since I rarely think to validate them manually.

As you've probably realized, the solution here is simply `s/patchcomment/comment/`. I'll get a fix out and in a v3.0.2 release shortly.

Any input of how to make the giant migration introduced in 3.0 welcome also!

**Comment by alialnu** [comment]
> As you've probably realized, the solution here is simply `s/patchcomment/comment/`. I'll get a fix out and in a v3.0.2 release shortly.
> 

Thanks!

> Any input of how to make the giant migration introduced in 3.0 welcome also!

Sorry, I don't understand. Do you mean to ask if my migration to 3.0 was successful? If so, then yes it was.

**Comment by stephenfin** [comment]
> > Any input of how to make the giant migration introduced in 3.0 welcome also!
> 
> Sorry, I don't understand. Do you mean to ask if my migration to 3.0 was successful? If so, then yes it was.

There was a big migration to remove the `Submission` model introduced in 3.0. I was concerned it might be very slow and that people would need to optimise things. It sounds like it was okay though, which is good news!

**Comment by alialnu** [comment]
Thanks @stephenfin

**Comment by alialnu** [comment]
Hi @stephenfin,
I'm retesting the migration from 2.2 to 3.0 again and getting:

```
$ sudo -u postgres -- psql -f lib/sql/grant-all.postgres.sql DATABASE_NAME
BEGIN
psql:lib/sql/grant-all.postgres.sql:38: ERROR:  relation "patchwork_comment" does not exist
psql:lib/sql/grant-all.postgres.sql:69: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:80: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:86: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:93: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:lib/sql/grant-all.postgres.sql:101: ERROR:  current transaction is aborted, commands ignored until end of transaction block
ROLLBACK
```

I see now that migration 0042 (introduced in 0686a736fbf6d869bd31bd135ba38080ac96de22) renamed the `Comment` model to `PatchComment`, meaning some of the table names changed in a51e7cfd95e24d6757a146e9c8e8f3aec44b226c were already correct, but reverting it causes the error in the description above.

I thought I tested your fix with v3.0 at the time, but maybe I did with a wrong code base or db version, sorry about that. 
I'll address it in a PR soon. Would you like to reopen the issue?

**Comment by stephenfin** [comment]
Yes, let's reopen

**Comment by alialnu** [comment]
Hi @stephenfin,
I didn't actually go through with the migration after the last discussion we had on this issue. I'm planning to migrate from stable/2.2 to stable/3.1 soon, but after additional testing, I see that the following exception reproduces when new comments arrive:
```
django.db.utils.ProgrammingError: permission denied for sequence patchwork_comment_id_seq
```
Both web and mail users are now missing privileges for this table, I just opened https://github.com/getpatchwork/patchwork/pull/533 to address it.

I apologize for not doing additional testing earlier, and I appreciate your help with this. Let me know what you think.
