### ISSUE TITLE
Checks API CRUD

### ISSUE THREAD

**Issue by tsipa** [getpatchwork/patchwork#398]
Hello, patchwork.

I'm trying to use PW checks api and i realized that i cannot update posted checks.
Is it by design or i'm missing something?

**Comment by stephenfin** [comment]
This is correct. The solution to update a check is to post a new one. The web UI and REST API will only show the last result for a given context

**Comment by tsipa** [comment]
I posted two checks here https://patchwork.kernel.org/project/netdevbpf/patch/20201028171506.15682-2-ardb@kernel.org/ with same context and they both displayed in the UI, am i doing it wrong?
https://patchwork.kernel.org/api/patches/11863443/checks/

**Comment by stephenfin** [comment]
Oh, that's interesting. I'll need to take a look at this over the weekend
