### ISSUE TITLE
RFC-2822 comments not handled in in-reply-to

### ISSUE THREAD

**Issue by djdelorie** [getpatchwork/patchwork#399]
RFC 2822 defines a "comment or folding white space" which is permitted to be inserted before or after the message-id in an In-Reply-To field (or in message-id or references)[1].  Neither the python email module nor patchwork seem to remove these comments, leading to lost email due to message id mismatches.

Example:  Emacs creates reply mails with fields like this:

```
In-Reply-To: <abcdef@example.com> (message from John Doe)
```

Testing (on patchwork 2.2 at least) has shown that manually removing the `(...)` part before sending causes patchwork to properly match emails to the correct patches.

[1] https://tools.ietf.org/html/rfc2822#section-3.6.4

**Comment by codonell** [comment]
This impacts glibc's use of patchwork. I really like using patchwork and we've built a good workflow and team for weekly patch queue review. It would be nice if this was fixed since it bites some of the developers working with emacs.

**Comment by daxtens** [comment]
Hi @stephenfin I have a potential volunteer for this bug, do you mind if they take it on?

**Comment by stephenfin** [comment]
> Hi @stephenfin I have a potential volunteer for this bug, do you mind if they take it on?

Go for it. I have a patch for this sitting somewhere, but I haven't gotten around to tidying it up yet

**Comment by daxtens** [comment]
Hi @djdelorie and @codonell, do either of you have some mboxes that show this behaviour? @raxelg has written a patch but I'd like to test it against some real mail if possible.

**Comment by djdelorie** [comment]
http://www.delorie.com/tmp/patchwork-399-1.txt

it's not in reply to a specific patch on our patchwork, but it was easy to find and has the right syntax :-)

**Comment by stephenfin** [comment]
Maybe it's just me, but that RFC is rather confusing. It defines the message-id, in-reply-to and references headers like so:

```
message-id      =       "Message-ID:" msg-id CRLF

in-reply-to     =       "In-Reply-To:" 1*msg-id CRLF

references      =       "References:" 1*msg-id CRLF

msg-id          =       [CFWS] "<" id-left "@" id-right ">" [CFWS]

id-left         =       dot-atom-text / no-fold-quote / obs-id-left

id-right        =       dot-atom-text / no-fold-literal / obs-id-right

no-fold-quote   =       DQUOTE *(qtext / quoted-pair) DQUOTE

no-fold-literal =       "[" *(dtext / quoted-pair) "]"
```

Expanding that out:

```
FWS             =       ([*WSP CRLF] 1*WSP) /   ; Folding white space
                        obs-FWS

ctext           =       NO-WS-CTL /     ; Non white space controls

                        %d33-39 /       ; The rest of the US-ASCII
                        %d42-91 /       ;  characters not including "(",
                        %d93-126        ;  ")", or "\"

ccontent        =       ctext / quoted-pair / comment

comment         =       "(" *([FWS] ccontent) [FWS] ")"

CFWS            =       *([FWS] comment) (([FWS] comment) / FWS)
```

However, later in that section, it states:

> Since the msg-id has
> a similar syntax to angle-addr (identical except that comments and
> folding white space are not allowed), a good method

Yes `angle-addr` is defined as:

```
angle-addr      =       [CFWS] "<" addr-spec ">" [CFWS] / obs-angle-addr
```

We can ignore the differences between `addr-spec` and ` id-left "@" id-right` for now, the fact that it explicitly calls out comments as not being allowed is weird. They're clearly allowed:

```
msg-id          =       [CFWS] "<" id-left "@" id-right ">" [CFWS]
```

So I'm not entirely sure how to interpret this. We're saying that this is valid:

```
In-Reply-To: <abcdef@example.com> (message from John Doe)
```

But what about this?

```
In-Reply-To: preamble here <abcdef@example.com> epilogue here that
 continues onto another line
```

Or what about this?

```
Message-ID: foo bar <stuff@xyz> baz
```

Should I simply be using `r'.*<([^>]+)>.*'` (i.e. drop everything outside the angle brackets)?

**Comment by stephenfin** [comment]
As another aside, that spec says:

```
references      =       "References:" 1*msg-id CRLF
```

But many mail applications includes a full list of previous messages' `Message-ID` fields here, so this should really read:

```
references      =       "References:" *msg-id CRLF
```

(or however you'd indicate 1 or more) if we wanted to reflect how email is done in the real world
