### ISSUE TITLE
2.2.5 release

### ISSUE THREAD

**Issue by tsipa** [getpatchwork/patchwork#417]
Hello.

I want to be able to use https://github.com/getpatchwork/patchwork/commit/49d0acc1e228d88cca68c78f7dce25c1d247732c on kernel.org. https://patchwork.kernel.org/ running 2.2.2 now. I have contacted admin(konstantin@linuxfoundation.org
) of kernel.org and he said he is okay to upgrade this instance as soon as 2.2.5 will be available with this fix.

Do you have a schedule or something which i can use to understand the timeline for 2.2.5? Can i contribute somehow to make it happen?
Right now the only difference between 2.2.4 and 2.2.5 is this exact commit - https://github.com/getpatchwork/patchwork/commits/stable/2.2

**Comment by stephenfin** [comment]
This is done now. Apologies for the delay.
