### ISSUE TITLE
Implement support for setting profiles to public for viewers such as viewer.scuttlebot.io

### ISSUE THREAD

**Issue by zadirion** [getpatchwork/patchwork#458]
Right now using ssb-server CLI to set it is impossible for any non-tech-savvy person. Having as much of the SSB network as possible visible through such web based viewers is very important for drawing in outside users. It should be an easy checkbox in the profile editing UI to mark the profile public for web viewers

**Comment by stephenfin** [comment]
What "profile" are you referring to?

**Comment by stephenfin** [comment]
I suspect you've got the wrong project here. I think you want [this project](https://github.com/ssbc/patchwork).
