### ISSUE TITLE
git-pw sometimes fetches same patch in series for two different patch numbers

### ISSUE THREAD

**Issue by sc00beyd00** [getpatchwork/patchwork#459]
When running git-pw patch apply on the first URL below it applies ok but the second URL still fetches the first patch.

https://patchwork.yoctoproject.org/project/oe/patch/1647524807-17685-1-git-send-email-xuhuan.fnst@fujitsu.com/

https://patchwork.yoctoproject.org/project/oe/patch/1647524807-17685-2-git-send-email-xuhuan.fnst@fujitsu.com/

Is there a client-side fix or is there something up with Patchwork?

**Comment by stephenfin** [comment]
This is expected behaviour in `git-pw`. It will automatically try to fetch series dependencies (i.e. previous patches in the series? for a patch. You can disable this behaviour with the `--no-deps` option.

**Comment by kraj** [comment]
@stephenfin even with `git-pw patch apply <number> -s` it will try to fetch series ? If so, thats a bit counter intuitive

**Comment by stephenfin** [comment]
What's the `-s` option? I assume that's a typo?

`git-pw patch apply` will attempt to apply the *dependencies* for a patch. The rationale is that you can't apply patch `X` of `Y` if you didn't apply `X-1`, `X-2`, etc. first. If you don't want this behavior, you can set up an alias in your `.bashrc` to set `--no-deps` by default.

**Comment by kraj** [comment]
`-s` is passed to git command underneath, which adds my sign-off-by to patch

**Comment by kraj** [comment]
> What's the `-s` option? I assume that's a typo?
> 
> `git-pw patch apply` will attempt to apply the _dependencies_ for a patch. The rationale is that you can't apply patch `X` of `Y` if you didn't apply `X-1`, `X-2`, etc. first. If you don't want this behavior, you can set up an alias in your `.bashrc` to set `--no-deps` by default.

yeah I get it though it did not come naturall, since there is also `git-pw series` command, so I thought `git-pw patch` is just to deal with single patches.

**Comment by stephenfin** [comment]
> `-s` is passed to git command underneath, which adds my sign-off-by to patch

Oh, of course.

> > What's the `-s` option? I assume that's a typo?
> > `git-pw patch apply` will attempt to apply the _dependencies_ for a patch. The rationale is that you can't apply patch `X` of `Y` if you didn't apply `X-1`, `X-2`, etc. first. If you don't want this behavior, you can set up an alias in your `.bashrc` to set `--no-deps` by default.
> 
> yeah I get it though it did not come naturall, since there is also `git-pw series` command, so I thought `git-pw patch` is just to deal with single patches.

Fair. I personally tend to apply individual patches rather than series because we've a gap in series support still (namely the inability to set a series state, which means `git pw series list` lists all patches *ever*). As I said, an alias will resolve this. I'll see if I can find some time to add a knob to control this behavior.

**Comment by kraj** [comment]
yes now I use
```
git-pw patch apply --no-deps $1 -s
```
