### ISSUE TITLE
'pwclient' proxy support

### ISSUE THREAD

**Issue by pjakma** [getpatchwork/patchwork#47]
I have an identical ~/.pwclientrc on two machines:

```
$ diff -u ~/.pwclientrc /tmp/.pwclientrc 
[paul@petrucci quagga] (proposed/tip)$ 
```

I have the same pwclient on the two macihnes:

```
$ (cd ~/bin; wget https://raw.githubusercontent.com/getpatchwork/patchwork/2671fc8752726d593c6f7e1deeb054961d74adee/patchwork/bin/pwclient)
```

One machine (fedora 22) it works fine (direct Internet), the other it does not (fedora 23):

```
$ pwclient projects
Traceback (most recent call last):
  File "/home/paul/bin/pwclient", line 807, in <module>
    main()
  File "/home/paul/bin/pwclient", line 732, in main
    action_projects(rpc)
  File "/home/paul/bin/pwclient", line 230, in action_projects
    projects = rpc.project_list("", 0)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1484, in parse_response
    p.feed(data)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 49
```

I have `http_proxy` and `https_proxy set`.

**Comment by stephenfin** [comment]
So proxy support isn't provided by default when using the ``xmlrpclib`` library in Python. It should be possible and there are [many tutorials|https://www.google.com/search?q=xmlrpclib+proxy] available for enabling this, but I wasn't able to get things running last time I checked.

I'm marking this as a feature request for now, seeing as we never said we did support proxies. If you could take a look into enabling this and perhaps submit a patch, that would be very helpful. If not, someone will eventually get around to it, but I don't know when that will be :disappointed:

**Comment by tmonjalo** [comment]
It is a serious issue.
What does mean the tag "ready"?

**Comment by stephenfin** [comment]
Indeed. Alas, I haven't had a chance to work on it and no longer work behind a proxy that I could test this with. `Ready` is a label from waffle.io indicating that the patch is ready for someone to work on it.

**Comment by tmonjalo** [comment]
Patch submitted: https://patchwork.ozlabs.org/patch/704688/
