### ISSUE TITLE
show patchwork ID in patch list/view

### ISSUE THREAD

**Issue by clandmeter** [getpatchwork/patchwork#48]
When browsing the webui, the patchwork ID is not displayed.
Is there a way to make it show in the interface in list view, and patch view?
Some browsers (safari) do not display the full url in the address bar, so its more convenient if it could displayed in ui when working with both ui and pwclient.

**Comment by ncopa** [comment]
screenshot: 
![skjermbilde 2016-07-20 kl 12 40 07](https://cloud.githubusercontent.com/assets/66357/16984283/5b32f8a6-4e79-11e6-97ab-afb557c2b3c8.png)

It would be nice to see the ID on the page so you know what ID to `pwclient git-am`

**Comment by ajdlinux** [comment]
We fixed this a few months ago - see https://github.com/getpatchwork/patchwork/commit/6e32965b04cc326a678a7b7a499f1389e44b6de9
