### ISSUE TITLE
Message-IDs with slashes in them breaks mbox download

### ISSUE THREAD

**Issue by djdelorie** [getpatchwork/patchwork#518]
See https://patchwork.sourceware.org/project/glibc/patch/Y%252F5wFE+YCYJ%252Fyr0j@morell/
The Message-ID is Y/5wFE+YCYJ/yr0j@morell

The "mbox" button doesn't work, but the "series" button does

Patch download in the event API is also broken:
https://patchwork.sourceware.org/api/1.3/series/17683/ (click on patch mbox tag)
(it's the same mbox URL, just trying to be complete ;)

**Comment by codonell** [comment]
This impacts part of the upstream glibc workflow, but only the part that tries to fetch the individual patches and apply them e.g. Patch Apply Bots.

Upstream kernel noticed this too:
https://people.kernel.org/monsieuricon/fix-your-mutt
And it is impacting public-inbox.

**Comment by codonell** [comment]
If / is valid in a message-id then I think we should handle it correctly with escaping, otherwise we're going to be chasing developers to fix their installations.

**Comment by stephenfin** [comment]
I thought we'd fixed this in https://github.com/getpatchwork/patchwork/issues/433. Are you using that patch? Did we miss a route?

**Comment by codonell** [comment]
@stephenfin Thank you for catching that! @siddhesh Have we updated our instance on Sourceware.org?

**Comment by siddhesh** [comment]
Our instance already has that fix, so I suspect we missed a route.

**Comment by stephenfin** [comment]
@siddhesh Did you ever get to the bottom of this?

**Comment by stephenfin** [comment]
This is now fixed and included in v3.1.3.
