### ISSUE TITLE
patchwork parses a lot of patch emails into two series

### ISSUE THREAD

**Issue by wanghao75** [getpatchwork/patchwork#529]
Question:
I have sent 370 emails of patch to my email host, in this step, unfortunately all emails have been two parts, and then I have used getmail tools to get them to patchwork, so the first parts of emails have been converted to series A in patchwork, the second parts of emails have been converted to series B in patchwork.

I want to know how to convert the second parts to series A in patchwork.

I need some help, thanks

**Comment by stephenfin** [comment]
We don't provide any tooling to do this as an end-user. You will need to ask an admin to merge the two series. They can do this using the admin view at `/admin` or via manual DB hacking. You can view server admins on the `/about` page in recent versions.

**Comment by wanghao75** [comment]
I will try what you say, thanks for your reply
