### ISSUE TITLE
Feature: handle merged patches

### ISSUE THREAD

**Issue by vincele** [getpatchwork/patchwork#530]
Would patchwork be able to somewhat handle merged patches ?
like it shows us the "A/R/T" status of a patch, I think it would be great if it could show us an additionnal "/M".

I dunno if it's possible or even easy to do it...

Maybe by adding & using an "Applied-by" tag, or what about an "Applied-to: $BRANCH"...

When a maintainer send the "merged, thanks" email, they could add such a tag in the email, that patchwork would then catch and display.

Sorry if this is a silly idea.

EDIT: Maybe that is what the "Accepted" Status is for, and I don't see it used in the ML that I follow...
EDIT2: Looks like "Accepted" is extensively use in some MLs, and less or not at all in some others.

**Comment by stephenfin** [comment]
Yeah, patch states are intended for this. Core Patchwork has no logic for detecting changes in state, however, and it has to be done externally. We provide an [example post-receive hook for Git](https://patchwork.readthedocs.io/en/latest/deployment/installation/#optional-configure-your-vcs-to-automatically-update-patches) for doing this but you need to install it in the Git server. Alternatively, if you're using a managed Git server or software forge like GitLab, GitHub etc. you could write a simple daemon to receive webhook requests from these services and update Patchwork accordingly, but we don't have anything in-tree to do this.
