### ISSUE TITLE
Allow Pre-Commit CI bots to have less privileges than a Maintainer of the project

### ISSUE THREAD

**Issue by codonell** [getpatchwork/patchwork#531]
The glibc project uses pre-commit CI driven by a bot that reports checks via the patchwork REST API.

As part of a security review I tried to reduce the permission of the bots.

Unfortunately the bots were required to be marked as "Maintainers" for the project before they could add checks.

I would have expected that at a minimum the bot would only need add, change, delete, view checks, but this is not sufficient to use the REST API to edit a check.

**Comment by stephenfin** [comment]
This is a long-term goal within the project. Unfortunately no one has picked this up yet, nor have I had time to address it myself. It shouldn't be all that complex as Django itself has the idea of user roles and user permissions: it's just a case of configuring them. Someone's got to investigate it though...

Closing as a dupe of #14.

**Comment by ribalda** [comment]
@stephenfin , sorry for the newbie question, but what are the purpose of the user permissions, if we still have to give maint access.

![image](https://github.com/getpatchwork/patchwork/assets/562331/714f8b88-e7a5-440e-96d5-4ea76bee7b9e)
