### ISSUE TITLE
Patches endpoint reports series without name

### ISSUE THREAD

**Issue by danielocfb** [getpatchwork/patchwork#567]
I am looking at https://patchwork.kernel.org/project/netdevbpf/list/?series=792260&state=*. 
![screenshot-2023-10-11_14-00-12](https://github.com/getpatchwork/patchwork/assets/77694251/4c04bd84-74d3-495d-a11c-710c1cc17489)

When going through the [`patches` API endpoint](https://patchwork.readthedocs.io/en/latest/api/rest/schemas/v1.2/#get--api-1.2-patches-), it is reported to have no series name. I.e., the `series` part of the response looks like:
```
{'id': 792260, 'url': 'https://patchwork.kernel.org/api/1.2/series/792260/', 'web_url': 'https://patchwork.kernel.org/project/netdevbpf/list/?series=792260', 'date': '2023-10-11T17:03:13', 'name': None, 'version': 9, 'mbox': 'https://patchwork.kernel.org/series/792260/mbox/'}
```

Is it by design that the `name` attribute is unset? I don't see that mentioned in the documentation.

**Comment by stephenfin** [comment]
Are you noting the mismatch between the name of `Untitled series #792260` seen in the web UI and the fact that it's unset in the REST API? If so, yes, this is expected. The `Untitled series #xyz` piece is a placeholder for series without a name. This will happen if [the user didn't set a series name explicitly (not currently possible outside of the admin view), a cover letter wasn't received, and a `1/n` patch was not received](https://github.com/getpatchwork/patchwork/blob/f37bd869f766c1fff6457e7cc8f523114f3e297c/patchwork/models.py#L896-L928). My guess if that the other 8 patches in that series were not submitted or were dropped somewhere.
