### ISSUE TITLE
[Feature] Allow assigning commit ID to Accepted patches

### ISSUE THREAD

**Issue by sorki** [getpatchwork/patchwork#569]
Recently I was wondering if there's a good way to figure out commit ID of the patch when we only have patchwork URL. 

I realized patchwork has only a concept of patches but no ties to actual git repository so it is not straightforward to have these (the IDs are different when submitted to ML and when commited to the repository).

I think this could be implemented in similar manner as Checks - API call that would allow to assigning commit ID to the patch when it gets merged. This can then be automated by watching the git repository or via a client.

I propose adding this to the model, API and displaying on the page showing patch details bellow `Message-ID` or `State` field (but only if the patch is Accepted).

I'm willing to work on this if it broadly makes sense.

**Comment by stephenfin** [comment]
You can already do this using [the REST API](https://patchwork.readthedocs.io/en/latest/api/rest/schemas/v1.3/#patch--api-1.3-patches-id-) and I think the XML-RPC API. Using `git-pw`, for example:

```
git pw patch update --commit-ref <commit-ref> <patch-id>
```

Is there something else you'd need here?

**Comment by sorki** [comment]
Very nice, thank you!
