### ISSUE TITLE
Cannot filter patches without any delegate

### ISSUE THREAD

**Issue by tmonjalo** [getpatchwork/patchwork#60]
I was using a very convenient feature in the old patchwork that I cannot find in the version 1.1:

In the filter box, the delegate field can be filled on completion only. It would be more convenient to list the possible values in the drop-down (i.e. people who had some patches delegated to them) but it is not really my issue.
More importantly, I would like to be able to find the patches which are not delegated at all.
Is there a way to do this please?

I guess it is related to the call $('#delegate_input').selectize() in patchwork/templates/patchwork/filters.html and in patchwork/filters.py? Is allowEmptyOption of selectize to be considered?
There is also a bug entry for this option:
        https://github.com/selectize/selectize.js/issues/739

**Comment by geertu** [comment]
Also, the filter box is cleared (last selection lost) when changing the current filter.

**Comment by kvalo** [comment]
I'm also missing the feature to be able to find patches which have not been delegated. Before patchwork.kernel.org was updated to v2.1.0 I was able to find such patches with this link:

https://patchwork.kernel.org/project/linux-wireless/list/?state=1&delegate=-&order=date

But after the upgrade it doesn't work anymore, the list is just empty. In linux-wireless project we have multiple maintainers and this was a handy way for me to daily check and find all unassigned patches and assign them to the correct maintainer. This feature was really useful for me and I hope to get it back.

**Comment by horms** [comment]
Likewise, I am not able to work out how to filter patches which have not been delegated. This has created a hole in my workflow.

**Comment by stephenfin** [comment]
@kvalo @horms @geertu Yup, I just need to find the time to figure this out. JS isn't my strong point :disappointed: If any of you know a good JS dev who'd have time to look at this in the interim, I can definitely explain where I think the issue lies (I just haven't figured out how to _fix_ it yet)

**Comment by tmonjalo** [comment]
Thanks

**Comment by stephenfin** [comment]
This is included in v2.1.3 too. You probably want to update to that, @tmonjalo
