### ISSUE TITLE
Website is missing basic links

### ISSUE THREAD

**Issue by ppaalanen** [getpatchwork/patchwork#61]
The web page at http://jk.ozlabs.org/projects/patchwork/ does not have direct links to Github or the issue tracker. There is the git-clone command, but it's not a link, you have to guess you can use as a web URL and manually copy it to the address line.

Patchwork itself, as running on freedesktop.org, only links to http://jk.ozlabs.org/projects/patchwork/ via "about" page.

Having a clickable link to the github page for all of documentation, source code access and issue tracker would be very useful.

**Comment by stephenfin** [comment]
Sounds fair. I will request the main site be updated and update the About page for Patchwork. You will need to report a bug against the [freedesktop instance](https://github.com/dlespiau/patchwork) if you want that fixed there though.

**Comment by ppaalanen** [comment]
For deployment, ok, sure! Thanks!
IMO it would be enough for the main web site to have the proper links, but if you also want to add them to the About page, that would be very nice.

**Comment by jk-ozlabs** [comment]
Hey folks, I've updated http://jk.ozlabs.org/projects/patchwork/, with links to the github site, issue tracker, and docs repo (thanks for the ping, @stephenfin). 

Let me know if that's suitable, or if you'd prefer any other changes.

**Comment by stephenfin** [comment]
I think that was all that was requested. Thanks, @jk-ozlabs

**Comment by ppaalanen** [comment]
@jk-ozlabs Thank you very much!
