### ISSUE TITLE
Add a way to fix Series' state

### ISSUE THREAD

**Issue by ppaalanen** [getpatchwork/patchwork#62]
Wayland's Patchwork at freedesktop.org has lots of series "open", but many (majority?) of them are already dealt with. The series state in Patchwork is just wrong for whatever reason.

I would like to be able to fix series states easily, so that I could clean up the list of open series.

**Comment by stephenfin** [comment]
Howdy. The freedesktop instance is forked. You should report this as an issue against said fork, which can be found at https://github.com/dlespiau/patchwork

**Comment by ppaalanen** [comment]
Ok.

Does the mainstream Patchwork not have the Series feature at all?
Or it never needs manual state fixing?
Or it already implements manual state fixing?
Or it already has some other solution?

Maybe the mainstream solution would be easier to port to the fork than fix from scratch...
@dlespiau , nudge?

**Comment by stephenfin** [comment]
> Does the mainstream Patchwork not have the Series feature at all?

It does, but it functions differently.

> Or it never needs manual state fixing?
> Or it already implements manual state fixing?
> Or it already has some other solution?

Exactly - series in mainstream Patchwork don't have state associated with them as they're merely containers for patches. If you want to change the "state" of a series, you change the state of the contained patches.

> Maybe the mainstream solution would be easier to port to the fork than fix from scratch...

I doubt it. They're quite different so I don't imagine a "solution" could be ported from one version to the other. You'll have to work with Damien to resolve this there, I'm afraid.
