### ISSUE TITLE
 patchwork/tools/post-receive.hook uses parser.py as a script

### ISSUE THREAD

**Issue by trini** [getpatchwork/patchwork#63]
In attempting to use current top of tree to try out using the post-receive.hook script to automatically update project patches I found that parser.py can no longer be run as a script (per the CHANGELOG) but the hook as not been updated to work with the new way of using that functionality.

**Comment by stephenfin** [comment]
The patches found in [this bundle](https://patchwork.ozlabs.org/bundle/stephenfin/post-receive%20fixes/) (currently under review) should resolve this for you. If they do, feel free to add your `Tested-by` to said patches.

**Comment by stephenfin** [comment]
Resolved in master
