### ISSUE TITLE
Requires login every time I open it

### ISSUE THREAD

**Issue by aik** [getpatchwork/patchwork#65]
Yes, this does not happen often but still annoying.

**Comment by stephenfin** [comment]
Could you provide a little more information? What requires login?

**Comment by aik** [comment]
https://patchwork.ozlabs.org - if I do not open it for a few weeks, it requests login.

**Comment by stephenfin** [comment]
> https://patchwork.ozlabs.org - if I do not open it for a few weeks, it requests login.

Could you provide a screenshot?

**Comment by aik** [comment]
screen shot of what? login screen? what value will it have? :)

**Comment by stephenfin** [comment]
> https://patchwork.ozlabs.org - if I do not open it for a few weeks, it requests login.

This is no different to how any website works - your browser will expire credentials after some duration of not using them. I'm afraid we can't do anything about this.

**Comment by aik** [comment]
is not the timeout configurable on the server side?

**Comment by daxtens** [comment]
I *think* this is covered by https://docs.djangoproject.com/en/1.10/ref/settings/#session-cookie-age It defaults to 2 weeks. What do you think the timeout should be?

Maybe we can get a setting set for you on patchwork.ozlabs.org without changing the defaults for everyone - jk should be able to do that.

**Comment by aik** [comment]
A month would be enough. Ooor the website could redirect back to the page where I was where I clicked on "login". For example, I open http://patchwork.ozlabs.org/project/slof/list/ , then click on login and then I'd expect to be redirected back to http://patchwork.ozlabs.org/project/slof/list/ but instead I see http://patchwork.ozlabs.org/user/

Also, a minor thing - the browser remembers the password twice - for http and https versions, is that by design?

**Comment by daxtens** [comment]
I'll ping jk on IRC to change the cookie expiration. I think the redirect might be a bit complex but we can look into it...

I don't know why the password would be remembered twice - did we run the site over http at one point?

**Comment by ajdlinux** [comment]
@daxtens we *currently* run the site over http...

**Comment by daxtens** [comment]
Awkward.

**Comment by daxtens** [comment]
@aik Jeremy has fixed this on the ozlabs patchwork server. Let us know on irc if you have any further issues :)

**Comment by stephenfin** [comment]
This looks like it's resolved now so I'm going to close this. Thanks @daxtens
