### ISSUE TITLE
Better placement for download links

### ISSUE THREAD

**Issue by aik** [getpatchwork/patchwork#76]
This is a feature request actually, is there a better place for these?

For example, http://patchwork.ozlabs.org/patch/719029/
I am looking for an easy way to "download mbox", and the link to it is where the patch starts. If there are some comments and the patch itself is big enough, the beginning of the patch is somewhere in the page, not close to the top or bottom, you need to search for it, or create a bundle (which requires more clicks).

I'd suggest placing a link to download patch/mbox at the top or bottom of the page  OR  add a link to the patch  at the top (so it would be just one more click).

**Comment by stephenfin** [comment]
That sounds fair. I'm open to idea on where this should go/patches to fix this.

**Comment by stephenfin** [comment]
Fixed on `master`
