### ISSUE TITLE
Docs missing for Patchwork management commands

### ISSUE THREAD

**Issue by tmonjalo** [getpatchwork/patchwork#77]
Patchwork provides a number of utility tools that lack any form of documentation. This can be seen by running:

    ./manage.py --help

The following commands should be documented somewhere:

- `cron`
- `parsearchive`
- `parsemail`
- `rehash`
- `retag`

Note that basic documentation is included in each command:

    ./manage.py parsemail --help

**Comment by stephenfin** [comment]
This was resolved in the above commit
