### ISSUE TITLE
XML-RPC Client Library

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/patchwork#8]
_From @stephenfin on July 23, 2015 13:59_
# Overview

The pwclient tool uses contains a client for the patchwork XML-RPC interface. However, this limits its usability to this tool. By splitting out the XML-RPC interfacing code, we could make writing client tools a far simpler case.
# Dependencies

N/A
# Alternatives

This could probably be split into a separate project, if we so wanted. Alternatively, we could wait on #12 and generate an API for that instead.
# Useful Links
- [python-wordpress-xmlrpc Documentation](https://media.readthedocs.org/pdf/python-wordpress-xmlrpc/latest/python-wordpress-xmlrpc.pdf)
- [XML-RPC WordPress API](https://codex.wordpress.org/XML-RPC_WordPress_API)

_Copied from original issue: stephenfin/patchwork#24_

**Comment by mirh** [comment]
Btw comment is wrong since 4b41c609084eff2ab49e1a7501314a0fa57450c4

**Comment by stephenfin** [comment]
XML-RPC is dead. Long live REST.
