### ISSUE TITLE
Patchwork doesn't run on Xenial with system packages

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/patchwork#94]
_From [Mailing List](https://lists.ozlabs.org/pipermail/patchwork/2017-April/004161.html)_

> Hi,
> 
> If I try to run patchwork with system versions of packages on Xenial,
> I run in to problems.
> 
> Specifically, when I run with ENABLE_REST_API=True, I see the
> following error:
> 
> ImportError: Could not import
> 'django_filters.rest_framework.DjangoFilterBackend' for API setting
> 'DEFAULT_FILTER_BACKENDS'. ImportError: No module named
> rest_framework.
> 
> I suspect this is due to the version of DRF - apt search shows:
> 
>   python-djangorestframework/xenial 3.3.2-2 all
> 
> requirements-prod.txt lists the required version as 3.5 to 3.6.
> 
> This is something we really need to fix: ozlabs.org runs Debian, and
> if it doesn't run on Xenial it's not likely to run on Debian. And we
> really, really want ozlabs.org to be able to support the REST API.
> 
> Can we relax the drf requirement?
> 
> Regards,
> Daniel

We should support versions of `django-rest-framework` from 3.3 up.

**Comment by daxtens** [comment]
So, as I said in my more recent email, the most pressing part of this problem is that we have django-filters 0.11 on Xenial, and we need 0.15 for django_filters.rest_framework.

What do those filters add and what do we lose if we set DEFAULT_FILTER_BACKENDS to None?

**Comment by stephenfin** [comment]
Yes, to clarify we should support `django-rest-framework` from 3.3 up including the use of the legacy `DjangoFilterBackend` found in `rest_framework.filters`

**Comment by stephenfin** [comment]
Now fixed on `master` with above commits
