### ISSUE TITLE
Race condition in 'patchwork.tests.test_list.PatchOrderTest'

### ISSUE THREAD

**Issue by stephenfin** [getpatchwork/patchwork#97]
There appears to be a race condition in the tests that results in intermittent _travis.io_ failures. Recent failures include [#128](https://travis-ci.org/getpatchwork/patchwork/jobs/210590534), [#141](https://travis-ci.org/getpatchwork/patchwork/jobs/222255783) and [#148](https://travis-ci.org/getpatchwork/patchwork/jobs/222336680).

**Comment by daxtens** [comment]
I'm triaging old issues: does this still occur? I don't recall seeing it in my use of Travis.

**Comment by stephenfin** [comment]
I _think_ so but I had been side-stepping the issue by restarting builds so I've nothing to point to. I'll close for now and re-open if/when the issue reoccurs.

**Comment by stephenfin** [comment]
And it's gone again. Weeeeird
